name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: configure
      run: |
        chmod +x build.sh
        sudo apt install gcc tree -y
      
    - name: build
      run: ./build.sh

    - name: check
      run: tree .
